# Thanks for Grunt for template of this file!

# http://www.appveyor.com/docs/appveyor-yml

# Fix line endings in Windows. (runs before repo cloning)
init:
  - git config --global core.autocrlf input

# Test against these versions of Node.js.
environment:
  matrix:
    - nodejs_version: "0.10"
    - nodejs_version: "0.12"
    - nodejs_version: "5"
    - nodejs_version: "4"

# Allow failing jobs for bleeding-edge Node.js versions.
matrix:
  allow_failures:
    - nodejs_version: "0.10"
    - nodejs_version: "5"

# Install scripts. (runs after repo cloning)
install:
  # Get the latest stable version of Node 0.STABLE.latest
  - ps: Install-Product node $env:nodejs_version
  # Output useful info for debugging.
  - node --version
  - npm --version
  - git --version
  - svn --version
  # Install all dependencies
  - npm install

# Post-install test scripts.
test_script:
  - cmd: npm run ci

# Don't actually build.
build: off

# Set build version format here instead of in the admin panel.
version: "{build}"
